phpapache:
  environment:
    TZ: "Europe/Vienna"
    DEVSYSTEM: "docker"
    #XDEBUG_CONFIG: "remote_host=192.168.99.1"
  build: docker-compose/php-apache
  volumes:
    - "./:/var/www/html/"
  ports:
    - "80:80"